<?php
/**
 * @file
 * countries_and_states.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function countries_and_states_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'American Samoa',
    'description' => 'The territory of American Samoa.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '01f02845-ffeb-4b92-834c-f0736b7e6ad1',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'AS',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'New Jersey',
    'description' => 'The state of New Jersey.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '02481fbd-0fcd-4f3a-91e0-73561e2ffc57',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NJ',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Guam',
    'description' => 'The territory of Guam.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '03b35169-f0af-4766-9819-4f66653ee48d',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'GU',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'United States of America',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(),
  );
  $terms[] = array(
    'name' => 'Tlaxcala',
    'description' => 'The Mexican state of Tlaxcala.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '061b6351-e40f-4f2d-a80d-c80148d2c0b9',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'TLAX',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Texas',
    'description' => 'The state of Texas.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '06ea5977-1890-41d2-8695-8a72503a4e16',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'TX',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Micronesia',
    'description' => 'The federated states of Micronesia.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '06eee4fc-874a-465e-8a7d-2a511f7ea58b',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'FM',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Florida',
    'description' => 'The state of Florida.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0995a119-fa6a-41ac-bd49-46c6a00b432e',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'FL',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Ohio',
    'description' => 'The state of Ohio.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0a2e311c-38ef-46c7-9aab-81023c068c3b',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'OH',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'California',
    'description' => 'The state of California.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0a97db36-7bbf-43fb-a655-19f64b9480e1',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'CA',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Maine',
    'description' => 'The state of Maine.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0d7a646c-fbe1-4364-ad53-f6df411a5efe',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'ME',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Alabama',
    'description' => 'The state of Alabama.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0ea70691-35d8-4fb4-989c-bc396b556c78',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'AL',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Oklahoma',
    'description' => 'The state of Oklahoma.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '11d4ee87-32d4-49c9-a2e6-75d2055bdacc',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'OK',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Northern Mariana Islands',
    'description' => 'The territory of Northern Mariana Islands.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '14779866-600b-4b52-b411-58570422fd0c',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MP',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Washington',
    'description' => 'The state of Washington.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '17ec639b-594a-4973-adf4-314cdc4640d3',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'WA',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Prince Edward Island',
    'description' => 'The Canadian province of Prince Edward Island.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1892b47b-8548-456b-85ef-ce60a7049dfd',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'PE',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Newfoundland',
    'description' => 'The Canadian province of Newfoundland.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1be3ca8a-eb49-44fb-9920-83853b7d76ec',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NF',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'British Columbia',
    'description' => 'The Canadian province of British Columbia.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1c366e5c-a1fc-4853-9e89-e46a2ea01eff',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'BC',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Jalisco',
    'description' => 'The Mexican state of Jalisco.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1ccdc2c9-5c49-462f-9e7a-e1ebca4ca01d',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'JAL',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Oregon',
    'description' => 'The state of Oregon.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '232ee19c-0992-4f59-abd7-d546121ac887',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'OR',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Nayarit',
    'description' => 'The Mexican state of Nayarit.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '246b33fe-eb81-4b60-bca3-b72100a894f8',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NAY',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Queretaro de Arteaga',
    'description' => 'The Mexican state of Queretaro de Arteaga.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2815d7b6-5bf8-44b0-a681-e7c716aae907',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'QRO',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Northwest Territories',
    'description' => 'The Canadian province of Northwest Territories.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2ff1dbac-b326-4e80-9bce-64c4bb9377b0',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NT',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Delaware',
    'description' => 'The state of Delaware.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '34e3c198-c0a7-4475-b7c3-a49f008010ea',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'DE',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Palau',
    'description' => 'The republic of Palau.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '361f5b31-71ed-4249-a9a2-c6fd65d9498e',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'PW',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Kansas',
    'description' => 'The state of Kansas.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3636803a-dff6-4602-90c8-dcb54b9c4c3d',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'KS',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Campeche',
    'description' => 'The Mexican state of Campeche.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3821da64-0d5e-41b6-867a-f61d7f1458e3',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'CAM',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'New Brunswick',
    'description' => 'The Canadian province of New Brunswick.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3c255f3c-4cd3-42d9-b351-a880eea0d9c5',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NB',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Ontario',
    'description' => 'The Canadian province of Ontario.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '41dd5cd8-12d8-42b5-9927-734de49be21c',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'ON',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Tabasco',
    'description' => 'The Mexican state of Tabasco.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '48fb8642-b360-425d-b5b2-e6ef2e2ca658',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'TAB',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'North Carolina',
    'description' => 'The state of North Carolina.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4eb8a0f5-0bbd-488e-9ef0-58d479586134',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NC',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Guanajuato',
    'description' => 'The Mexican state of Guanajuato.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4ed71d08-6aa3-46e3-b72d-e53a51970fa4',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'GTO',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'New Mexico',
    'description' => 'The state of New Mexico.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4f59adbd-def1-4374-becf-bf2ebc41aa24',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NM',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Arkansas',
    'description' => 'The state of Arkansas.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '554a4f60-405d-4837-a99a-51dffd445fcb',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'AR',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'The Mexican Distrito Federal',
    'description' => 'The Mexican Distrito Federal.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '57ade634-482f-4db7-b9af-26621173898b',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'DF',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Pennsylvania',
    'description' => 'The state of Pennsylvania.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5acea2a9-b97c-4751-b850-ca13e235f6b2',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'PA',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Iowa',
    'description' => 'The state of Iowa.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5cbe28ff-1c6b-41b5-9cb4-eeb880b805a7',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'IA',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Puerto Rico',
    'description' => 'The territory of Puerto Rico.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5eeeafc0-0ef1-4bc5-945e-f9f9358e89a1',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'PR',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Sinaloa',
    'description' => 'The Mexican state of Sinaloa.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '60218715-8cea-4daf-83d0-6f129b40716e',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'SIN',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'New Hampshire',
    'description' => 'The state of New Hampshire.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6395fad0-fbab-46f4-85bc-2192c0bbbbe0',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NH',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Alberta',
    'description' => 'The Canadian province of Alberta.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '641c0d4b-02fb-4f51-970e-9280124530ca',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'AB',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'New York',
    'description' => 'The state of New York.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '67f788eb-a51e-4c8d-a159-500f6595b26e',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NY',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Zacatecas',
    'description' => 'The Mexican state of Zacatecas.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '68b7a77c-5d6c-4091-bd19-1d10b0d711d8',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'ZAC',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Maryland',
    'description' => 'The state of Maryland.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '70ae0d18-d5e7-4413-a876-c7ccab334a10',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MD',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Nebraska',
    'description' => 'The state of Nebraska.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '71bb11e5-6b7f-45e1-a8a3-5fd417b8b19a',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NE',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Baja California',
    'description' => 'The Mexican state of Baja California.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '71ccbb9e-f9c3-4a1b-ba6e-557c1901dc24',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'BC',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Veracruz-Llave',
    'description' => 'The Mexican state of Veracruz-Llave.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '72121914-53cc-4e99-a3a7-5845d1af0be8',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'VER',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Montana',
    'description' => 'The state of Montana.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '72e44730-da23-4630-9aff-8a4c60cd59e5',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MT',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Saskatchewan',
    'description' => 'The Canadian province of Saskatchewan.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '76ab6c20-0b3f-4a89-b439-e096669a8456',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'SK',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Mexico',
    'description' => 'The Mexican state of Mexico.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MEX',
          'format' => 'plain_text',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Rhode Island',
    'description' => 'The state of Rhode Island.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '821d7e39-87ea-4c70-8902-6fa6441d643d',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'RI',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Mississippi',
    'description' => 'The state of Mississippi.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '83b92938-b8c7-4622-b156-ae8cb8188b4a',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MS',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Tennessee',
    'description' => 'The state of Tennessee.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '851ff7d9-5ddd-46a7-8538-4eb107e5ef47',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'TN',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Utah',
    'description' => 'The state of Utah.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8c5dd14c-58a7-4c6a-bc0c-376a0bfc322f',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'UT',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Morelos',
    'description' => 'The Mexican state of Morelos.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8ca30a1e-696d-46de-8acf-72664a975ecf',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MOR',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Yukon Territory',
    'description' => 'The Canadian province of Yukon Territory.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8d201c59-6dfe-4b0d-a8f5-2274928d0d81',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'YT',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Hildalgo',
    'description' => 'The Mexican state of Hildalgo.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8d4ba329-2edb-4d31-a210-3ea58d0a2e1c',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'HGO',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Coahuila de Zaragoza',
    'description' => 'The Mexican state of Coahuila de Zaragoza.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8d5a5b1e-0262-4346-84c2-5f99d5ec3999',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'COAH',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Yucatan',
    'description' => 'The Mexican state of Yucatan.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9536723e-f2e8-4f67-abb3-5d714153b106',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'YUC',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Baja California Sur',
    'description' => 'The Mexican state of Baja California Sur.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9b88d183-2282-4106-ac71-ea92b6a1e493',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'BCS',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Nevada',
    'description' => 'The state of Nevada.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9c691b10-6e95-4931-922a-93124b595bbe',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NV',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Virginia',
    'description' => 'The state of Virginia.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a051af38-e83e-481e-bb3d-3db8fe5d3ee9',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'VA',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Michigan',
    'description' => 'The state of Michigan.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a559c3fe-89f9-4824-84db-422364316266',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MI',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Chiapas',
    'description' => 'The Mexican state of Chiapas.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a76cae23-7322-4931-81a5-4adb1c13d773',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'CHIS',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Illinois',
    'description' => 'The state of Illinois.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a92c1b96-752e-4ea7-b05f-c7eca43cd015',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'IL',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Hawaii',
    'description' => 'The state of Hawaii.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a9fc3f13-48c7-4d34-9896-ea213f5ef81e',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'HI',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'West Virginia',
    'description' => 'The state of West Virginia.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'af39f854-9741-454e-914a-b7fa2e934e56',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'WV',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Puebla',
    'description' => 'The Mexican state of Puebla.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b0158cad-3304-4666-b510-19bcb90b10e7',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'PUE',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'North Dakota',
    'description' => 'The state of North Dakota.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b04854a1-ea5e-4b89-8b55-9d6815bac3cf',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'ND',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Idaho',
    'description' => 'The state of Idaho.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b6386a4b-f2c6-4d29-ba48-ba9cba608168',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'ID',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Missouri',
    'description' => 'The state of Missouri.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b7287858-7662-4330-9b78-e3880c93825b',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MO',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Manitoba',
    'description' => 'The Canadian province of Manitoba.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b8191282-3b0c-40bc-9fcc-ca2122367d1c',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MB',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Indiana',
    'description' => 'The state of Indiana.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b86b8e56-cf50-4a2d-bf1f-f25f6def0c58',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'IN',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Nuevo Leon',
    'description' => 'The Mexican state of Nuevo Leon.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bb1a2258-edd0-405a-90e1-f4a1f23e8e89',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NL',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Louisiana',
    'description' => 'The state of Louisiana.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bf7bffaf-77e0-4159-8fd9-ebdceeca87da',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'LA',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Quebec',
    'description' => 'The Canadian province of Quebec.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c072deb9-2bd1-40ef-bcaa-14f6345c7e0f',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'PQ',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Minnesota',
    'description' => 'The state of Minnesota.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c2cbcaf0-14e5-4c2d-90d3-f15e50ca0c90',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MN',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Colorado',
    'description' => 'The state of Colorado.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c68acc5b-02c9-4d4f-8824-84e1232b1028',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'CO',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Michoacan de Ocampo',
    'description' => 'The Mexican state of Michoacan de Ocampo.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c6caf7ba-2744-495a-bd4b-e5926be6fd14',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MICH',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Connecticut',
    'description' => 'The state of Connecticut.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c7466953-8461-408f-8eb3-237a4953938d',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'CT',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'US Minor Outlying Islands',
    'description' => 'The territory of U.S. Minor Outlying Islands.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c99d65ad-43ab-4d9a-936d-a9e005ff22fd',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'UM',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Oaxaca',
    'description' => 'The Mexican state of Oaxaca.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ca6c01b8-3d06-475a-b2f9-49082ed5953f',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'OAX',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Aguascalientes',
    'description' => 'The Mexican state of Aguascalientes.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'cb6ef282-095c-4d91-bbda-725f9282ad97',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'AGS',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Nova Scotia',
    'description' => 'The Canadian province of Nova Scotia.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'cdc07623-df22-43b4-b1ff-5e1b6b532e26',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NS',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'Tamaulipas',
    'description' => 'The Mexican state of Tamaulipas.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'cdd6e930-7d0f-4f60-847e-2aa9ce629629',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'TAMPS',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'South Dakota',
    'description' => 'The state of South Dakota.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ce71e30d-8df4-4b5f-9d03-f7fec152c3f2',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'SD',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Wisconsin',
    'description' => 'The state of Wisconsin.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd1e714ae-022c-44df-b769-ec6529078a25',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'WI',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Kentucky',
    'description' => 'The state of Kentucky.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd5ee6ae3-7a14-41e3-b17f-1cea893707fb',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'KY',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Virgin Islands of the United States',
    'description' => 'The territory of the Virgin Islands of the United States.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd5fc4c46-7245-4bc5-9bf4-a8610a746047',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'VI',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Massachusetts',
    'description' => 'The state of Massachusetts.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd94ffd5e-58a0-4fa7-97ca-557ce7e82113',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MA',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Alaska',
    'description' => 'The state of Alaska.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd9c8fbdf-0f5a-40ca-8904-c12e11da3e9c',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'AK',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Quintana Roo',
    'description' => 'The Mexican state of Quintana Roo.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'df0b37b7-9fc8-4a39-8c18-043885176691',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'QROO',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Canada',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(),
  );
  $terms[] = array(
    'name' => 'Marshall Islands',
    'description' => 'The republic of the Marshall Islands.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e74fe788-3f5f-444d-960f-0dbaa3fbc16f',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'MH',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Wyoming',
    'description' => 'The state of Wyoming.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e83d04fc-8f4f-4a42-8527-38ce2d759539',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'WY',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Arizona',
    'description' => 'The state of Arizona.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ed9afabf-f312-4fef-b901-1714afb8a984',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'AZ',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Sonora',
    'description' => 'The Mexican state of Sonora.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f0ceec52-8292-4c54-ab58-c0d93ca468d7',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'SON',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Colima',
    'description' => 'The Mexican state of Colima.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f4f72e0e-eb0f-4a2f-9bbf-f3c39c10d2b1',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'COL',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Durango',
    'description' => 'The Mexican state of Durango.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f7eb081b-c6e0-44a1-8b1c-a9712de000ba',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'DGO',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Nunavut',
    'description' => 'The Canadian territory of Nunavut.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f7f5eb29-6273-44f2-a47a-e929f0043597',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'NU',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => 'e64caced-bbaf-4f47-b7cb-02db8d955882',
    ),
  );
  $terms[] = array(
    'name' => 'District of Columbia',
    'description' => 'The state of District of Columbia.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f85009d2-1306-448a-bf00-57d560daf4ff',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'DC',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'South Carolina',
    'description' => 'The state of South Carolina.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f8b61d80-2a4c-4e13-b530-0cb6e651ee9c',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'SC',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'Georgia',
    'description' => 'The state of Georgia.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fb57f07d-a382-4cc3-9f9b-d935b04c92dd',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'GA',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  $terms[] = array(
    'name' => 'San Luis Potosi',
    'description' => 'The Mexican state of San Luis Potosi.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fc52be70-6709-4f97-93ce-466db1ffdd7a',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'SLP',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Chihuahua',
    'description' => 'The Mexican state of Chihuahua.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fc6e77f0-6668-4132-92ac-7067ddc6a5ce',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'CHIH',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Guerrero',
    'description' => 'The Mexican state of Guerrero.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fd6556c3-a6f7-4b25-b95d-d2efe695d3e4',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'GRO',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '799c3c0e-72b3-43c0-bd0b-05b3aee3be39',
    ),
  );
  $terms[] = array(
    'name' => 'Vermont',
    'description' => 'The state of Vermont.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ffc170f6-1b6d-485a-89d5-3185a20fcdbb',
    'vocabulary_machine_name' => 'countries_and_states',
    'field_abbreviation' => array(
      'und' => array(
        0 => array(
          'value' => 'VT',
          'format' => 'plain_text',
        ),
      ),
    ),
    'parent' => array(
      0 => '051d9e4a-48c1-48e2-b879-d8d7dc5aa7ba',
    ),
  );
  return $terms;
}
